sudo: false
language: go
go: [ 1.13.x ]

env:
  - GO111MODULE=on

install:
  # Stop go get from executing
  - true

script:
  - go get -u golang.org/x/lint/golint
  - golint ./...
  - go test ./...

  # Build for various architectures
  - GOARCH=amd64 GOOS=windows make && mv dist/dots{,-windows-amd64.exe}
  - GOARCH=amd64 GOOS=darwin  make && mv dist/dots{,-macos-amd64}
  - GOARCH=amd64 GOOS=linux   make && mv dist/dots{,-linux-amd64}
  - GOARCH=arm64 GOOS=linux   make && mv dist/dots{,-linux-arm64}

before_deploy:
  # Replace dev-build tag with latest release
  - export OWNER=${TRAVIS_REPO_SLUG%/*}
  - git remote add gh https://${OWNER}:${GITHUB_API_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
  - git tag -f dev-build
  - git push -f gh dev-build
  - git remote remove gh

deploy:
  - provider: releases
    api-key: $GITHUB_API_TOKEN
    name: Development Build
    body: Automatic development build of the master branch.
    file:
      - dist/dots-windows-amd64.exe
      - dist/dots-macos-amd64
      - dist/dots-linux-amd64
    prerelease: true
    overwrite: true
    skip_cleanup: true
    target_commitish: $TRAVIS_COMMIT
    on:
      tags: false
      branch: release/2.x
