name: build
on: [push, create]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ^1.13

      - name: Checkout tags
        run: |
          git fetch --prune --unshallow
          git fetch origin +refs/tags/*:refs/tags/*

      - name: Lint
        uses: golangci/golangci-lint-action@v3

      - name: Lint shell code
        run: shellcheck -e SC2155 scripts/bootstrap

      - name: Test
        run: go test ./...

      - name: Build
        run: |
          GOARCH=amd64 GOOS=windows make && mv dist/dots{,-windows-amd64.exe}
          GOARCH=amd64 GOOS=darwin  make && mv dist/dots{,-macos-amd64}
          GOARCH=arm64 GOOS=darwin  make && mv dist/dots{,-macos-arm64}
          GOARCH=amd64 GOOS=linux   make && mv dist/dots{,-linux-amd64}

      - name: Release latest master
        if: github.event_name == 'push'
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: dev-build
          prerelease: true
          title: Development Build
          files: |
            scripts/bootstrap
            dist/dots-linux-amd64
            dist/dots-macos-amd64
            dist/dots-macos-arm64
            dist/dots-windows-amd64.exe

      - name: Release tagged version
        if: github.event_name == 'create' && startsWith(github.ref, 'refs/tags')
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            scripts/bootstrap
            dist/dots-linux-amd64
            dist/dots-macos-amd64
            dist/dots-macos-arm64
            dist/dots-windows-amd64.exe
